<MainWindow>:
    id: main_window

    ScreenManager:
        id: screen_manager_main

        Screen:
            id: screen_escolheridioma
            name: 'screen_escolheridioma'

        Screen:
            id: screen_paginaprincipal
            name: 'screen_paginaprincipal'

        Screen:
            id: screen_escolherpais
            name: 'screen_escolherpais'

        Screen:
            id: screen_quiz
            name: 'screen_quiz'
