PerguntaBRPT = {
    1: 'Que prato típico brasileiro é um bolinho feito de feijão-fradinho e recheado com vinagrete, camarão e outros ingredientes?',
    2: 'Que prato típico é geralmente associado ao estado de Minas Gerais?',
    3: 'Que receita típica do sudeste brasileiro foi criada em 1937 e é um sanduíche feito com pão francês e geralmente recheado com queijo e presunto ou com finos filés de carne?',
    4: 'Qual desses pratos não possui camarão como um de seus ingredientes?',
    5: 'Que famoso prato foi criado no norte de Portugal e hoje é um dos pratos mais típicos da culinária brasileira? ',
    6: 'Qual festa tradicional brasileira é comemorada antes da estação litúrgica da quaresma?',
    7: 'Qual festa tradicional brasileira é caracterizada por danças em volta da fogueira?',
    8: 'Em qual cidade da Bahia se localiza o famoso Elevador Lacerda? ',
    9: 'Em qual estado se localiza as Cataratas do Iguaçu?',
    10: 'Qual ponto turístico brasileiro está na lista das Sete Maravilhas do Mundo Moderno? ',
    11: 'Em que estado fica o Lago de Furnas?',
    12: 'Qual personagem do folclore brasileiro é relacionado ao fogo e, em sua história, costumava ser uma pessoa que foi transformada por uma maldição?',
    13: 'Quem é o escritor nascido no Rio de Janeiro e considerado por muitos o maior nome da literatura brasileira?',
    14: 'Qual é o nome do famoso cantor brasileiro compositor da música “O descobridor dos sete mares”?',
    15: 'Quem é o personagem do folclore brasileiro conhecido pela forma animal e por raptar crianças desobedientes que não querem dormir?',
    16: 'Qual músico brasileiro chegou a fazer parceria com o cantor Frank Sinatra? ',
    17: 'Qual carta foi elaborada na conferência das Nações Unidas sobre o meio ambiente, ocorrida no Brasil, conhecida como Rio-92? ',
    18: 'Qual é o maior bioma do Brasil?',
    19: 'Qual era o objetivo da Agenda 21?',
    20: 'Qual personagem do folclore brasileiro é híbrido entre humano e peixe e é famoso por seu canto? ',
    21: 'Qual é a cidade mais populosa do Brasil?',
    22: 'Qual foi o primeiro nome do Brasil?',
    23: 'Quem foi o primeiro presidente da República no Brasil?',
    24: 'Qual é o maior estado do Brasil?',
    25: 'Qual foi o primeiro time de futebol brasileiro a conquistar o título da Libertadores?',
    26: 'Quem declarou a independência do Brasil? ',
    27: 'Qual é o estilo de dança mais popular do Brasil? ',
    28: 'Qual é a capital do Brasil?',
    29: 'Em que ano os Jogos Olímpicos foram sediados no Brasil?',
    30: 'Qual dessas siglas representa o sistema público de saúde do Brasil? ',
    31: 'O Sus conquistou muitos avanços para a saúde do Brasil, qual desses é o mais reconhecido internacionalmente?',
    32: 'Qual é a moeda circulante no Brasil, atualmente? ',
    33: 'Quais foram os dois presidentes a sofrer impeachment no Brasil? ',
    34: 'Quais são as capitais dos seguintes estados: Amazonas, Espírito Santo, Santa Catarina, Amapá e Goiás. ',
    35: 'Qual foi a primeira capital do Brasil?',
    36: 'Quem assinou a Lei Áurea, que decretou a abolição da escravatura no Brasil? ',
    37: 'Qual é o rio mais extenso do Brasil?',
    38: 'Quem foi o presidente do Brasil durante o período da Segunda Guerra Mundial? ',
    39: 'Em que ano a Seleção Brasileira foi campeã da Copa do Mundo pela primeira vez? ',
    40: 'Qual é o menor estado brasileiro? ',
    41: 'Contra que país o Império do Brasil, juntamente com a Argentina e o Uruguai, travou uma guerra entre 1864 e 1870?',
    42: 'Que ritmo musical e dança brasileira se originou no estado de Pernambuco? ',
    43: 'O primeiro elevador urbano do mundo se encontra na cidade de Salvador. Qual é o nome desse elevador? ',
    44: 'Em extensão territorial, o Brasil é o... ',
    45: 'O que significa IBGE? ',
    46: 'Quais países, junto ao Brasil, fizeram parte da Tríplice Aliança na Guerra do Paraguai?',
    47: 'Qual desses biomas é exclusivamente brasileiro? ',
    48: 'Qual é o nome oficial do Brasil?',
    49: 'Quem foi responsável pelo projeto arquitetônico do MASP, Museu de Arte de São Paulo Assis Chateubriand? ',
    50: 'Em que cidade fica a Catedral de São Pedro de Alcântara, em que há um sarcófago duplo com os restos do imperador D. Pedro II e da imperatriz D. Teresa Cristina? '
}

PerguntaBRES = {
    1: '¿Qué plato típico brasileño es una bolita hecha de frijoles refritos y rellena de vinagreta, camarones y otros ingredientes?',
    2: '¿Qué plato típico se suele asociar al estado de Minas Gerais?',
    3: '¿Qué receta típica del sudeste de Brasil fue creada en 1937 y es un sándwich hecho con pan francés y generalmente relleno de queso y jamón o con finas lonchas de carne?',
    4: '¿Cuál de estos platos no tiene gambas como uno de sus ingredientes?',
    5: '¿Qué famoso plato fue creado en el norte de Portugal y es hoy uno de los más típicos de la cocina brasileña?',
    6: '¿Qué fiesta tradicional brasileña se celebra antes del tiempo litúrgico de la Cuaresma?',
    7: '¿Qué fiesta tradicional brasileña se caracteriza por el baile alrededor de la hoguera?',
    8: '¿En qué ciudad de Bahía se encuentra el famoso ascensor Lacerda?',
    9: '¿En qué estado se encuentran las cataratas de Iguazú?',
    10: '¿Qué atracción turística brasileña está en la lista de las siete maravillas del mundo moderno?',
    11: '¿En qué estado se encuentra el lago Furnas?',
    12: '¿Qué personaje del folclore brasileño está relacionado con el fuego y, en su historia, era una persona transformada por una maldición?',
    13: '¿Quién es el escritor nacido en Río de Janeiro y considerado por muchos el mayor nombre de la literatura brasileña?',
    14: '¿Cómo se llama el famoso cantante brasileño que compuso la canción "O descobridor dos sete mares"?',
    15: '¿Quién es el personaje del folclore brasileño conocido por su forma animal y por secuestrar a los niños desobedientes que no quieren dormir?',
    16: '¿Qué músico brasileño ha trabajado con el cantante Frank Sinatra?',
    17: '¿Qué carta se elaboró en la conferencia de las Naciones Unidas sobre el medio ambiente celebrada en Brasil, conocida como Río-92?',
    18: '¿Cuál es el bioma más grande de Brasil?',
    19: '¿Cuál fue el propósito de la Agenda 21?',
    20: '¿Qué personaje del folclore brasileño es un híbrido entre humano y pez y es famoso por su canto?',
    21: '¿Cuál es la ciudad más poblada de Brasil?',
    22: '¿Cuál era el primer nombre de Brasil?',
    23: '¿Quién fue el primer presidente de la República en Brasil?',
    24: '¿Cuál es el estado más grande de Brasil?',
    25: '¿Cuál fue el primer equipo de fútbol brasileño en ganar la Copa Libertadores?',
    26: '¿Quién declaró la independencia de Brasil?',
    27: '¿Cuál es el estilo de baile más popular en Brasil?',
    28: '¿Cuál es la capital de Brasil?',
    29: '¿En qué año se celebraron los Juegos Olímpicos en Brasil?',
    30: '¿Cuál de estas siglas representa el sistema de salud pública en Brasil?',
    31: '¿Sus ha logrado muchos avances para la salud en Brasil, ¿cuál de ellos es el más reconocido internacionalmente?',
    32: '¿Cuál es la moneda que circula actualmente en Brasil?',
    33: '¿Qué dos presidentes han sido destituidos en Brasil?',
    34: 'Cuáles son las capitales de los siguientes estados: Amazonas, Espírito Santo, Santa Catarina, Amapá y Goiás.',
    35: '¿Cuál fue la primera capital de Brasil?',
    36: '¿Quién firmó la Lei Áurea, que decretó la abolición de la esclavitud en Brasil?',
    37: '¿Cuál es el río más largo de Brasil?',
    38: '¿Quién era el presidente de Brasil durante la Segunda Guerra Mundial?',
    39: '¿En qué año ganó la selección brasileña la Copa del Mundo por primera vez?',
    40: '¿Cuál es el estado brasileño más pequeño?',
    41: '¿Contra qué país hizo la guerra el Imperio brasileño, junto con Argentina y Uruguay, entre 1864 y 1870?',
    42: '¿Qué ritmo musical y danza brasileña se originó en el estado de Pernambuco?',
    43: 'El primer ascensor urbano del mundo se encuentra en la ciudad de Salvador. ¿Cómo se llama este ascensor?',
    44: 'En extensión territorial, Brasil es el...',
    45: '¿Qué significa IBGE?',
    46: '¿Qué países, junto con Brasil, formaron parte de la Triple Alianza en la Guerra del Paraguay?',
    47: '¿Cuál de estos biomas es exclusivamente brasileño?',
    48: '¿Cuál es el nombre oficial de Brasil?',
    49: '¿Quién fue el responsable del proyecto arquitectónico del MASP, el Museo de Arte de São Paulo Assis Chateubriand?',
    50: '¿En qué ciudad se encuentra la Catedral de San Pedro de Alcántara, donde hay un doble sarcófago con los restos del emperador Pedro II y la emperatriz Teresa Cristina?'
}

PerguntaEQBR = {
    1: 'Qual dessas comidas típicas não é do Equador? ',
    2: 'Qual desses pratos não possui peixes ou frutos do mar? ',
    3: 'Qual desses não é uma sobremesa? ',
    4: 'Qual desses não é uma sopa? ',
    5: 'Qual desses alimentos não é feito e/ou acompanhado de banana? ',
    6: 'Qual desses pode ser considerado uma competição premiada entre cowboys? ',
    7: 'Qual desses também pode ser conhecido por festival da lua?',
    8: 'Qual dessas é considerada a festa mais alegre na cidade mais amável do país? ',
    9: 'Qual das alternativas é uma representação do ano e é feito para simbolizar o ano que termina? ',
    10: 'Qual das alternativas é uma expressão cultural única no país, sendo hoje declarado Patrimônio Cultural Imaterial do Equador? ',
    11: 'Personagem do folclore equatoriano, era um indígena que nos tempos coloniais ficou encarregado da construção do átrio da Igreja de São Francisco em Quito. ',
    12: 'Qual animal foi descoberto recentemente no Equador? ',
    13: 'Em qual lugar do Equador a iniciativa Yasuní-ITT trabalhou contra a exploração do petróleo? ',
    14: 'Qual arquipélago que pertence ao equador é Patrimônio Natural da Humanidade? ',
    15: 'Qual festa foi criada após o prejuízo sofrido do terremoto de 5 de Agosto 1949, pelos habitantes da província de Tungurahua (Ambato – Equador)?',
    16: 'Qual é a maior montanha do Equador? ',
    17: 'Qual é a maior praia do Equador? ',
    18: 'Qual cidade teve seu centro histórico como Patrimônio Cultural da Humanidade pela Unesco?',
    19: 'Como se chama o maior conjunto de ruínas incas do país? ',
    20: 'Qual é a capital do Equador? ',
    21: 'Qual é a moeda do Equador? ',
    22: 'Quem compôs o hino do Equador? ',
    23: 'Quem foi o primeiro presidente do Equador?',
    24: 'Qual foi o primeiro time de futebol campeão equatoriano da Libertadores? ',
    25: 'Qual é a maior província, em área, do Equador? ',
    26: 'Qual é a província mais populosa do Equador? ',
    27: 'Qual a capital do Equador? ',
    28: 'O Equador continental é frequentemente considerado como três regiões geográficas. São elas a Costa, a Serra e a...',
    29: 'Quais países fazem fronteira com o Equador?',
    30: 'Quem foi a primeira mulher a se tornar presidente do Equador, mesmo que por apenas poucos dias? ',
    31: 'Que país invadiu o Equador em 1941? ',
    32: 'Qual desses não é uma província do Equador? ',
    33: 'Qual desses se trata de um dispositivo eletrônico que permite aos cegos determinar a distância dos objetos?',
    34: 'Qual das opções pretende tornar o aprendizado da geometria mais prático? ',
    35: 'Qual desses animais é uma nova espécie de carnívoro que vive nas florestas nubladas dos Andes equatorianos? ',
    36: 'A UTPL, Universidad Técnica Particular de Loja, possui quantos laboratórios de protótipos?',
    37: 'O Ministério da Saúde Pública e as instituições da Rede Pública aplicarão ... nas áreas  aprovadas pelo Ministério das Relações do Trabalho, que consiste no pagamento de um percentual adicional de 20% ou 10%. Qual o nome desta norma de pagamento percentual?',
    38: 'Qual é o nome da famosa batalha ocorrida no dia 24 de maio de 1822?',
    39: 'Quem descobriu as Ilhas Galápagos?',
    40: 'Como se chama o famoso lago equatoriano formado em uma caldeira de um vulcão? ',
    41: 'Qual oceano banha o Equador? ',
    42: 'Como se chama o monumento construído para marcar o ponto onde se acreditava que a linha do equador atravessava o país?',
    43: 'Qual é o nome do chapéu mais tradicional no Equador, feito há mais de 100 anos? ',
    44: 'O Equador é conhecido por ser a capital mundial de qual planta? ',
    45: 'Qual é o nome do pássaro do brasão do Equador? ',
    46: 'Qual língua nativa do Equador é mais falada?',
    47: 'Como se chama a festa tradicional equatoriana celebrada em agradecimento à Pachamama pelas flores e frutas? ',
    48: 'Em que província equatoriana é realizado o festival tradicional La Mama Negra?',
    49: 'Como se chama a cadeia montanhosa ou cordilheira passa pelo centro do Equador?',
    50: 'Junto de quais outros países o Equador fez parte da Grã-Colômbia?'
}

PerguntaEQES = {
    1: '¿Cuáles de estos alimentos típicos no son de Ecuador?',
    2: '¿Cuál de estos platos no tiene pescado o marisco?',
    3: '¿Cuál de estos no es un postre?',
    4: '¿Cuál de estos no es sopa?',
    5: '¿Cuál de estos alimentos no está elaborado y / o acompañado de plátanos?',
    6: '¿Cuál de estos podría considerarse una competencia preciada entre vaqueros?',
    7: '¿Cuál de estos también se puede conocer como el festival de la luna?',
    8: '¿Cuál de estas se considera la fiesta más feliz en la ciudad más amigable del país?',
    9: '¿Cuál de las alternativas es una representación del año y está destinada a simbolizar el año final?',
    10: '¿Cuál de las alternativas es una expresión cultural única en el país, siendo hoy declarado Patrimonio Cultural Inmaterial del Ecuador?',
    11: 'Personaje del folklore ecuatoriano, fue un indígena que en la época colonial fue el encargado de construir el atrio de la Iglesia de São Francisco en Quito.',
    12: '¿Qué animal fue descubierto recientemente en Ecuador?',
    13: '¿En qué parte de Ecuador protegió la Iniciativa Yasuní-ITT contra la exploración petrolera?',
    14: '¿Qué archipiélago perteneciente al ecuador es Patrimonio Natural de la Humanidad?',
    15: '¿Qué festival se creó tras los daños sufridos por los habitantes de la provincia de Tungurahua (Ambato - Ecuador) por el terremoto del 5 de agosto de 1949?',
    16: '¿Cuál es la montaña más grande de Ecuador?',
    17: '¿Cuál es la playa más grande del Ecuador?',
    18: '¿Qué ciudad tuvo su centro histórico como Patrimonio de la Humanidad por la Unesco?',
    19: '¿Cómo se llama el conjunto de ruínas incas más grande del país?',
    20: '¿Cuál es la capital de Ecuador?',
    21: '¿Cuál es la moneda de Ecuador?',
    22: '¿Quién compuso el himno de Ecuador?',
    23: '¿Quién fue el primer presidente de Ecuador?',
    24: '¿Cuál fue el primer equipo de fútbol ecuatoriano en ganar la Libertadores?',
    25: '¿Cuál es la provincia más grande, en superficie, de Ecuador?',
    26: '¿Cuál es la provincia más poblada de Ecuador?',
    27: '¿Cuál es la capital de Ecuador?',
    28: 'El ecuador continental suele considerarse como tres regiones geográficas. Se trata de la Costa, la Sierra y la...',
    29: '¿Qué países tienen frontera con Ecuador?',
    30: '¿Quién fue la primera mujer que llegó a la presidencia de Ecuador, aunque sólo fuera por unos días?',
    31: '¿Qué país invadió Ecuador en 1941?',
    32: '¿Cuál de ellas no es una provincia de Ecuador?',
    33: '¿Cuál de estos es un dispositivo electrónico que permite a las personas ciegas determinar la distancia de los objetos?',
    34: '¿Cuál de las opciones pretendes hacer más práctico el aprendizaje de la geometría?',
    35: '¿Cuál de estos animales es una nueva especie de carnívoro que vive en los bosques nubosos de los Andes ecuatorianos?',
    36: '¿Cuántos laboratorios de prototipos tiene la UTPL, Universidad Técnica Particular de Loja?',
    37: 'El Ministerio de Salud Pública y las instituciones de la Red Pública aplicarán ... en áreas aprobadas por el Ministerio de Relaciones Laborales, que consiste en un pago porcentual adicional del 20% o del 10%. ¿Cómo se llama esta regla de pago porcentual?',
    38: '¿Cómo se llama la famosa batalla que tuvo lugar el 24 de mayo de 1822?',
    39: '¿Quién descubrió las Islas Galápagos?',
    40: '¿Cómo se llama el famoso lago ecuatoriano formado en la caldera de un volcán?',
    41: '¿Qué océano bordea el ecuador?',
    42: '¿Cómo se llama el monumento construido para marcar el punto en el que se creía que el ecuador cruzaba el país?',
    43: '¿Cómo se llama el sombrero más tradicional de Ecuador, fabricado desde hace más de 100 años?',
    44: '¿Ecuador es conocido por ser la capital mundial de qué planta?',
    45: '¿Cómo se llama el ave del escudo de Ecuador?',
    46: '¿Qué idioma nativo de Ecuador es el más hablado?',
    47: '¿Cómo se llama la fiesta tradicional ecuatoriana que se celebra en agradecimiento a la Pachamama por las flores y los frutos?',
    48: '¿En qué provincia ecuatoriana se celebra la tradicional fiesta de la Mama Negra?',
    49: '¿Cómo se llama la cordillera que atraviesa el centro de Ecuador?',
    50: '¿Con qué otros países formaba Ecuador parte de la Gran Colombia?'
}

DicaBR = {
    1: 'É um prato especialmente famoso na Bahia. // Es un plato especialmente famoso en Bahía.',
    2: 'É recheado com queijo. // Se rellena con queso.',
    3: 'Tem o mesmo nome de uma cidade do estado de São Paulo. // Tiene el mismo nombre que una ciudad del estado de São Paulo.',
    4: 'É um prato do sudeste brasileiro relacionado ao estado de São Paulo. // Es un plato del sudeste brasileño relacionado con el estado de São Paulo.',
    5: 'Em sua versão brasileira, ele é feito com feijão preto e geralmente leva carne seca e/ou linguiça em seus ingredientes. // En su versión brasileña, se hace con frijoles negros y suele incluir carne seca y/o salchichas en sus ingredientes.',
    6: 'É a festa mais famosa do país e envolve o uso de fantasias. // Es la fiesta más famosa del país y conlleva el uso de disfraces.',
    7: 'É comemorada especialmente no nordeste do pais e tem como característica a vestimenta caricata de caipira. // Se celebra especialmente en el noreste del país y se caracteriza por la caricatura del traje de caipira.',
    8: 'Fica na mesma cidade em que se encontra o Pelourinho. // Está en la misma ciudad que el Pelourinho.',
    9: 'Está na região sul do país. // Se encuentra en la región sur del país.',
    10: 'Fica localizado no Rio de Janeiro. // Se encuentra en Río de Janeiro.',
    11: 'É um estado conhecido por cidades da era colonial que remetem à corrida do ouro no país.  // Es un estado conocido por las ciudades de la época colonial que se remontan a la fiebre del oro del país.',
    12: 'É um animal. // Es un animal.',
    13: 'É famoso por obras como “Dom Casmurro” e “Memórias Póstumas de Brás Cubas”. // Es famoso por obras como "Dom Casmurro" y "Memórias Póstumas de Brás Cubas".',
    14: 'Seu nome real é Sebastião Rodrigues Maia. // Su verdadero nombre es Sebastião Rodrigues Maia.',
    15: 'Sua representação mais famosa foi feita na série “Sítio do Picapau Amarelo”. // Su representación más famosa se realizó en la serie "Sítio do Picapau Amarelo".',
    16: 'Foi um dos compositores da música “Garota de Ipanema”. // Fue uno de los compositores de la canción "Garota de Ipanema".',
    17: 'É uma declaração de princípios éticos fundamentais para a construção de uma sociedade global justa, sustentável e pacífica. // Es una declaración de principios éticos fundamentales para la construcción de una sociedad global justa, sostenible y pacífica.',
    18: 'Ele se estende por nove países da América do Sul. // Se extiende por nueve países sudamericanos.',
    19: 'É um documento que foi assinado durante a Rio-92. // Es un documento que se firmó durante Río-92.',
    20: 'Esse personagem canta para atrair suas vítimas. // Este personaje canta para atraer a sus víctimas.',
    21: 'Está situada na região sudeste do país e é a capital de um estado. // Está situada en el sureste del país y es la capital de un estado.',
    22: 'Recebeu esse nome porque a expedição de Pedro Álvares Cabral carregava lascas do que se supunha ser a verdadeira cruz em que Cristo fora crucificado. // Su nombre se debe a que la expedición de Pedro Álvares Cabral llevaba astillas de lo que se suponía era la verdadera cruz en la que fue crucificado Cristo.',
    23: 'Foi um militar e teve participação na Proclamação da República. // Fue militar y participó en la Proclamación de la República.',
    24: 'Fica situado na região norte do país. // Se encuentra en la región norte del país.',
    25: 'Foi o primeiro clube de Pelé, que começou a jogar pelo time aos quinze anos de idade. // Fue el primer club de Pelé, que empezó a jugar en el equipo a los quince años.',
    26: 'Era o filho do rei João VI de Portugal. // Era hijo del rey João VI de Portugal.',
    27: 'Possuí origens africanas. // Su origen es africano.',
    28: 'Foi projetada principalmente por Oscar Niemeyer e inaugurada em 1960, pelo governo de Juscelino Kubitschek. // Fue diseñado principalmente por Oscar Niemeyer e inaugurado en 1960 por el gobierno de Juscelino Kubitschek.',
    29: 'O evento foi realizado no Rio de Janeiro. // El evento se celebró en Río de Janeiro.',
    30: 'Foi criado em 1988 e sua sigla significa Sistema Único de Saúde. // Fue creado en 1988 y sus siglas significan Sistema Único de Salud.',
    31: 'É o responsável por 98% do mercado de vacinas do país. // Representa el 98% del mercado de vacunas del país.',
    32: 'Foi implantada no dia 1 de julho de 1994, durante o governo do presidente Fernando Henrique Cardoso. // Se implantó el 1 de julio de 1994, durante el gobierno del Presidente Fernando Henrique Cardoso.',
    33: 'Os mandatos dos dois presidentes foram iniciados, respectivamente, em 1990 e 2011. // Los mandatos de los dos presidentes comenzaron en 1990 y 2011 respectivamente.',
    34: 'As capitais são iniciadas pelas seguintes letras, respectivamente: M, V, F, M, G. // Las capitales comienzan con las siguientes letras respectivamente: M, V, F, M, G.',
    35: 'Fica no estado da Bahia. // Se encuentra en el estado de Bahía.',
    36: 'Era filha do imperador Pedro II. // Era hija del emperador Pedro II.',
    37: 'Com 6.436 quilômetros de comprimento, ele percorre o norte da América do Sul, a floresta amazônica e deságua no Oceano Atlântico. // Con 6.436 kilómetros de longitud, atraviesa el norte de Sudamérica, la selva amazónica y desemboca en el océano Atlántico.',
    38: 'Impôs uma ditadura no país e morreu em 1954, cometendo suicídio. // Impuso una dictadura en el país y murió en 1954, suicidándose.',
    39: 'Foi na sexta edição da Copa do Mundo, sediada na Suécia. // Fue en la sexta edición de la Copa del Mundo, celebrada en Suecia.',
    40: 'Fica na costa da região nordeste. // Se encuentra en la costa de la región noreste.',
    41: 'É um país que não tem saída para o mar e, na época, era comandado por Francisco Solano López. // Es un país sin salida al mar y en ese momento estaba comandado por Francisco Solano López.',
    42: 'Se caracteriza pelo ritmo extremamente acelerado e incorpora elementos de outras danças, como maxixe, polca e, inclusive, a capoeira. Além de ter ganhado o título de Patrimônio Imaterial da Humanidade pela UNESCO, em 2012. // Se caracteriza por un ritmo extremadamente rápido e incorpora elementos de otros bailes, como el maxixe, la polka e incluso la capoeira. Además de haber obtenido el título de Patrimonio Inmaterial de la Humanidad por la UNESCO en 2012.',
    43: 'Ele foi inaugurado em 1873 e criado pelos irmãos Antônio Francisco de Lacerda e Augusto Frederico de Lacerda. // Fue inaugurado en 1873 y creado por los hermanos Antônio Francisco de Lacerda y Augusto Frederico de Lacerda.',
    44: 'Na lista de países por extensão territorial o Brasil se encontra uma posição atrás dos Estados Unidos. // En la lista de países por superficie, Brasil está un puesto por detrás de Estados Unidos.',
    45: 'É um instituto que tem suas atribuições ligadas às geociências e estatísticas sociais, demográficas e econômicas, o que inclui realizar censos e organizar as informações obtidas nesses censos. // Es un instituto que tiene sus atribuciones vinculadas a las geociencias y a las estadísticas sociales, demográficas y económicas, lo que incluye la realización de censos y la organización de la información obtenida de los mismos.',
    46: 'Esses países possuem como capital, respectivamente, as cidades de Buenos Aires e Montevidéu. // Las capitales de estos países son, respectivamente, Buenos Aires y Montevideo.',
    47: 'Esse bioma ocupa 11% do território nacional e pode ser encontrado nos estados do nordeste do Brasil e no extremo norte de Minas Gerais. // Este bioma ocupa el 11% del territorio nacional y se encuentra en los estados del noreste de Brasil y en el extremo norte de Minas Gerais.',
    48: 'Esse nome foi instituído pela Constituição de 1967, mantido pela Emenda Constitucional nº 1, outorgado pela junta militar de 1969, e pela constituição de 1988. // Este nombre fue instituido por la Constitución de 1967, mantenido por la Enmienda Constitucional nº 1, concedida por la junta militar en 1969, y por la Constitución de 1988.',
    49: 'Foi uma arquiteta modernista ítalo-brasileira, naturalizada no Brasil após a Segunda Guerra Mundial. // Fue una arquitecta modernista italo-brasileña, nacionalizada en Brasil tras la Segunda Guerra Mundial.',
    50: 'Essa cidade se encontra no estado do Rio de Janeiro e é conhecida como Cidade Imperial, isso porque devido às suas temperaturas amenas e belezas naturais, se tornou um refúgio de verão para a realeza na época do Império. // Esta ciudad se encuentra en el estado de Río de Janeiro y es conocida como la Ciudad Imperial, ya que por sus suaves temperaturas y su belleza natural, se convirtió en un refugio de verano para la realeza en la época del Imperio.'
}

DicaEQ = {
    1: 'É um cozido, na maioria das vezes de peixe, e é típico da culinária brasileira e da culinária angolana. // Es un guiso, principalmente pescado, y es típico de la cocina brasileña y angoleña.',
    2: 'É feito com creme adicionado leite, e pode ser servido com queijo fresco e é uma sopa. // Está hecho con crema de leche agregada y se puede servir con queso fresco y es una sopa.',
    3: 'É Preparado com frutas típicas e especiarias para criar a bebida espessa de cor amora. // Se prepara con frutas y especias típicas para crear una bebida espesa de color mora.',
    4: 'É um tipo de roedor que geralmente é acompanhado de arroz e banana madura frita. // Es un tipo de roedor que suele ir acompañado de arroz y plátanos maduros fritos.',
    5: 'É uma tortilha preparada inicialmente ralando mandiocas e depois as espremendo com a sënoriya, um instrumento em forma de lenço feito com a fibra da árvore senorijati. // Es una tortilla preparada inicialmente rallando la yuca y luego exprimiéndola con el sënoriya, un instrumento en forma de bufanda elaborado con la fibra de un árbol del lugar llamado sënorijati.',
    6: 'É uma tradição nascida dos vaqueiros habitantes das zonas rurais da costa equatoriana. // Es una tradición que nace de los vaqueros que viven en zonas rurales de la costa ecuatoriana.',
    7: 'Acontece no ponto culminante da preparação do terreno para o plantio. // Tiene lugar en la culminación de la preparación del terreno para la siembra.',
    8: 'É uma combinação da devoção à Virgem Maria de Monserrate e a gratidão a Pacha Mama pela fecundidade das terras. // Es una combinación de devoción a la Virgen María de Monserrate y agradecimiento a Pacha Mama por la fertilidad de la tierra.',
    9: 'É representado por um boneco feito com roupas velhas e recheados com serragem, ou feitos com papelão, jornal e pintado com tinta. // Está representado por una muñeca hecha de ropa vieja y rellena de aserrín, o hecha de cartón, periódico y pintada con tinta.',
    10: 'Tem os seus jogos compostos por personagens (demônios, casais da linha de guarichas, capariches) que dançam tanto em suas comunidades de origem quanto nas principais ruas do cantão de Píllaro. // Tiene sus juegos compuestos por personajes (demonios, parejas de la línea guarichas, caprichosos) que bailan tanto en sus comunidades de origen como en las calles principales del cantón de Píllaro.',
    11: 'Fez um pacto com o diabo para finalizar a construção no prazo estipulado. // Hizo un trato con el diablo para terminar la construcción dentro del período estipulado.',
    12: 'Carnívoro nativo das florestas altas e enevoadas da Colômbia e do Equador. // Carnívoro originario de los bosques altos y brumosos de Colombia y Ecuador.',
    13: 'Fica na ecorregião de florestas úmidas de Napo. // Está en la ecorregión de la selva tropical de Napo.',
    14: 'Foi visitado pelo naturalista Charles Darwin em 1835. // Fue visitada por el naturalista Charles Darwin en 1835.',
    15: 'Acontece aproximadamente entre fevereiro ou março. // Ocurre aproximadamente entre febrero o marzo.',
    16: 'Situa-se perto de Riobamba, a cerca de 180 km ao sul de Quito.',
    17: 'É a praia mais próxima da capital, Quito e possui praia de areias escuras, ondas médias. // Es la playa más cercana a la capital, Quito, y tiene playas de arena oscura y oleaje medio.',
    18: 'É uma cidade na cordilheira dos Andes, no sul do Equador. // Es uma ciudad de la cordillera de los Andes en el sur de Ecuador.',
    19: 'Fica localizado na pequena província de Cañar. // Se encuentra en la pequeña provincia de Cañar.',
    20: 'Conhecida pelo centro colonial bem preservado, rico com igrejas dos séculos XVI e XVII. // ¿Conocido por su centro colonial bien conservado, rico em inglesias de los siglos XVI y XVII.',
    21: 'É a moeda oficial dos EUA. // Es la moneda oficial de los Estados Unidos.',
    22: 'Nasceu em Córsega, na França. // Nació en Córcega, Francia.',
    23: 'Foi um general venezuelano que tornou-se chefe supremo do Equador e depois o primeiro presidente do Equador. // Fue un general venezolano que llegó a ser jefe supremo de Ecuador y luego el primer presidente de Ecuador.',
    24: 'É um time de Quito fundado oficialmente em 1930. // Es un equipo quiteño fundado oficialmente en 1930.',
    25: 'Sua capital é Puyo, e seu nome foi dado em função do rio que o separa da província de Morona-Santiago. // Su capital es Puyo, y recibe su nombre del río que la separa de la provincia de Morona-Santiago.',
    26: 'Sua capital é Guayaquil. // Su capital es Guayaquil.',
    27: 'É a segunda cidade mais populosa do Equador. // Es la segunda ciudad más poblada de Ecuador.',
    28: 'Fica ao leste do Equador. // Se encuentra al este del ecuador.',
    29: 'As iniciais desses países são, respectivamente, P e C. // Las iniciales de estos países son P y C respectivamente.',
    30: 'Foi eleita como vice-presidente de Abdalá Bucaram e assumiu a presidência após Bucaram ser impedido de governar. // Fue elegida como vicepresidenta de Abdallah Bucaram y asumió la presidencia después de que a Bucaram se le impidiera gobernar.',
    31: 'Esse país faz fronteira com o Equador. // Este país es fronterizo con Ecuador.',
    32: 'É na verdade um principado localizado na Espanha, conhecido pela costa acidentada, pelas montanhas, pelos locais religiosos e pela arquitetura medieval. // En realidad, es un principado situado en España, conocido por su escarpada costa, sus montañas, sus lugares religiosos y su arquitectura medieval.',
    33: 'Ele é usado por meio de um sensor, evitando assim viagens e acidentes, ajudando os usuários a serem autossuficientes e mais seguros. // Se lleva mediante un sensor, lo que evita tropiezos y accidentes, ayudando a los usuarios a ser autosuficientes y más seguros.',
    34: 'É o primeiro brinquedo inventado e patenteado do Equador composto de teorias matemáticas. // Es el primer juguete inventado y patentado en Ecuador y compuesto por teorías matemáticas.',
    35: 'O animal, que é fisicamente muito parecido com o consumo (Potos flavus), sofre há mais de 100 anos um caso de identidade equivocada. // El animal, que es físicamente muy parecido al consumo (Potos flavus), sufre un caso de confusión de identidad desde hace más de 100 años. ',
    36: 'São locais equipados para produzir pela primeira vez ideias, produtos, marcas, etc. Por isso atuam em mais de 10 áreas diferentes. // Son lugares equipados para producir ideas, productos, marcas, etc. por primera vez, por lo que trabajan en más de 10 áreas diferentes.',
    37: 'Ele ocorre devido aos locais de trabalho que se localizam em zonas de difícil acesso ou são enquadradas nesta forma devido a condições geográficas particulares. // Ocurre por lugares de trabajo que se ubican en áreas de difícil acceso o están enmarcados en esta norma debido a condiciones geográficas particulares.',
    38: 'Ocorreu no sopé do vulcão Pichincha, a mais de 3.000 metros de altitude, nos arredores da cidade de Quito. // Tuvo lugar al pie del volcán Pichincha, a más de 3.000 metros de altura, en las afueras de la ciudad de Quito.',
    39: 'Foi o quarto bispo do Panamá. // Fue el cuarto obispo de Panamá.',
    40: 'O mirante fica localizado a 3,900m acima do nível do mar na pequena vila de mesmo nome do vulcão. // El mirador está situado a 3.900 m de altitud en el pequeño pueblo del mismo nombre que el volcán.',
    41: 'É o maior oceano do mundo. // Es el mayor océano del mundo.',
    42: 'O monumento tem 30 metros de altura e foi construído entre 1979 e 1982 pelo Conselho da Província de Pichincha. // El monumento tiene 30 metros de altura y fue construido entre 1979 y 1982 por el Consejo Provincial de Pichincha.',
    43: 'A palha do chapéu é conhecida como palha Toquilla. // La paja del sombrero se conoce como paja toquilla.',
    44: 'Há mais de 4.000 espécies dessa planta no Equador. // Hay más de 4.000 especies de esta planta en Ecuador.',
    45: 'É a maior ave voadora do mundo e a que tem a terceira maior envergadura de asas, com 3,3 metros. // Es el ave voladora más grande del mundo y tiene la tercera mayor envergadura, con 3,3 metros.',
    46: 'Era falado na região central dos Andes desde bem antes da época do Império Inca. // Se habla en los Andes centrales desde mucho antes de la época del Imperio Inca.',
    47: 'Também é conhecida como “festival do florescimento” e seus principais elementos são a água e as flores. Nessa cerimônia são realizados diversos rituais e cantos. // También se conoce como la "fiesta del florecimiento" y sus elementos principales son el agua y las flores. En esta ceremonia se realizan varios rituales y cantos.',
    48: 'O festival ocorre em setembro e novembro e homenageia a Virgen de la Merced, que, em 1742, teria impedido a erupção do vulcão homônimo à província em que o festival é realizado. // La fiesta se celebra en septiembre y noviembre y rinde homenaje a la Virgen de la Merced, de quien se dice que en 1742 evitó la erupción del volcán que lleva el mismo nombre que la provincia en la que se celebra la fiesta.',
    49: 'É a maior cadeia montanhosa do mundo em comprimento e se estende desde a Venezuela até a região da Patagônia, passando pelo território de 7 países. // Es la cordillera más larga del mundo y se extiende desde Venezuela hasta la región de la Patagonia, pasando por el territorio de 7 países.',
    50: 'A Grã-Colômbia foi um país que existiu legalmente entre 1821 e 1831, as iniciais dos atuais países que fizeram parte dela são: V, C, P e. // La Gran Colombia fue un país que existió legalmente entre 1821 y 1831, las siglas de los actuales países que formaron parte de ella son: V, C, P y E.'
}

RespotaBRPT = {
    1: ['Acarajé', 'Cachorro-quente', 'Fogaça', 'Moqueca', 'Acarajé'],
    2: ['Coxinha', 'Pão de queijo', 'Empada', 'Pastel', 'Pão de queijo'],
    3: ['Misto quente', 'Beirute', 'X-burguer', 'Bauru', 'Bauru'],
    4: ['Tacacá', 'Acarajé', 'Caruru', 'Virado à paulista', 'Virado à paulista'],
    5: ['Feijoada', 'Moqueca', 'Tutu de feijão', 'Baião de dois', 'Feijoada'],
    6: ['Festa Junina', 'Carnaval', 'Semana Santa', 'Festa do Bonfim', 'Carnaval'],
    7: ['Festa do Peão', 'Bumba meu Boi', 'Congada', 'Festa Junina', 'Festa Junina'],
    8: ['Salvador', 'Feira de Santana', 'Porto Seguro', 'Presidente Dutra', 'Salvador'],
    9: ['Mato Grosso', 'Paraná', 'Santa Catarina', 'Minas Gerais', 'Paraná'],
    10: ['Pão de Açúcar', 'Pico da Bandeira', 'Catedral da Sé', 'Cristo Redentor', 'Cristo Redentor'],
    11: ['Minas Gerais', 'Rio de Janeiro', 'Amazonas', 'Goiás', 'Minas Gerais'],
    12: ['Boitatá', 'Curupira', 'Mula sem Cabeça', 'Boto-cor-de-rosa', 'Mula sem Cabeça'],
    13: ['Carlos Drummond de Andrade', 'Manuel Bandeira', 'Mário de Andrade', 'Machado de Assis', 'Machado de Assis'],
    14: ['Tim Maia', 'Jorge Ben Jor', 'Chico Buarque', 'Wilson Simonal', 'Jorge Ben Jor'],
    15: ['Papa-Figo ou Homem do Saco', 'Cuca', 'Iara', 'Caboclo d’Água', 'Cuca'],
    16: ['Tom Jobim', 'Caetano Veloso', 'Toquinho', 'João Gilberto', 'Tom Jobim'],
    17: ['Carta das Nações Unidas', 'Carta da Terra', 'Acordo Ortográfico de 1990', 'Pacto do ABC', 'Carta da Terra'],
    18: ['Pantanal', 'Pampas', 'Caatinga', 'Amazônia', 'Amazônia'],
    19: ['Desenvolvimento Alimentar', 'Acordo Nuclear', 'Plano Educacional', 'Desenvolvimento Sustentável', 'Desenvolvimento Sustentável'],
    20: ['Boto cor-de-rosa', 'Boiuna', 'Iara', 'Mapinguari', 'Iara'],
    21: ['São Paulo', 'Belo Horizonte', 'Brasília', 'Salvador', 'São Paulo'],
    22: ['Terra de Santa Cruz', 'Ilha de Vera Cruz', 'Estados Unidos do Brasil', 'Reino Unido de Portugal, Brasil e Algarves', 'Ilha de Vera Cruz'],
    23: ['Dom Pedro II', 'Marechal Deodoro da Fonseca', 'Getúlio Vargas', 'Itamar Franco', 'Marechal Deodoro da Fonseca'],
    24: ['Amazonas', 'Bahia', 'Mato Grosso', 'Pará', 'Amazonas'],
    25: ['Palmeiras', 'Cruzeiro', 'Santos', 'São Paulo', 'Santos'],
    26: ['Dom Pedro I', 'Pedro Álvares Cabral', 'Dom Pedro II', 'Marechal Deodoro', 'Dom Pedro I'],
    27: ['Xaxado', 'Frevo', 'Maxixe', 'Samba', 'Samba'],
    28: ['São Paulo', 'Rio de Janeiro', 'Salvador', 'Brasília', 'Brasília'],
    29: ['2016', '2010', '2014', '2008', '2016'],
    30: ['Anvisa', 'IBGE', 'IML', 'SUS', 'SUS'],
    31: ['Programa Nacional de Imunizações (PNI)', 'Registro Nacional de Doadores de Medula Óssea (REDOME)', 'Samu 192', 'RAPS', 'Programa Nacional de Imunizações (PNI)'],
    32: ['Real', 'Cruzeiro', 'Cruzeiro novo', 'Réis', 'Real'],
    33: ['Fernando Collor e Dilma Roussef', 'Dilma Roussef e José Sarney', 'Fernando Collor e Juscelino Kubitschek', 'Itamar Franco e Michel Temer', 'Fernando Collor e Dilma Roussef'],
    34: ['Manaus, Vitória, Fortaleza, Macapá, Goiânia.', 'Manaus, Vitória, Florianópolis, Macapá, Goiânia.', 'Amazônia, Vitória, Curitiba, Boa Vista, Brasília.', 'Rio Branco, Vitória, Porto Velho, Teresina, Distrito Federal.', 'Manaus, Vitória, Florianópolis, Macapá, Goiânia.'],
    35: ['Porto Velho', 'Rio de Janeiro', 'São Paulo', 'Salvador', 'Salvador'],
    36: ['Princesa Isabel', 'D. Leopoldina', 'Pedro I do Brasil', 'Maria Tomásia Figueira Lima', 'Princesa Isabel'],
    37: ['Rio Paraná', 'Rio São Francisco', 'Rio Madeira', 'Rio Amazonas', 'Rio Amazonas'],
    38: ['Nilo Peçanha', 'Getúlio Vargas', 'Eurico Gaspar Dutra', 'Washington Luís', 'Getúlio Vargas'],
    39: ['1950', '1958', '1962', '1954', '1958'],
    40: ['Alagoas', 'Paraná', 'Sergipe', 'Acre', 'Sergipe'],
    41: ['Bolívia', 'Paraguai', 'Venezuela', 'Colombia', 'Paraguai'],
    42: ['Samba', 'Carimbó', 'Baião', 'Frevo', 'Frevo'],
    43: ['Elevador de Salvador', 'Elevador de Matte', 'Elevador Lacerda', 'Elevador Municipal', 'Elevador Lacerda'],
    44: ['Maior país do mundo', '3º maior país do mundo', '5º maior país do mundo', 'd) 6º maior país do mundo', '5º maior país do mundo'],
    45: ['Instituto Brasileiro de Geografia e Estatística', 'Instituto Brasileiro de Geometria e Estatística', 'Instituto do Brasil Geológico Estadual', 'Instituição Brasileira de Gráficos e Estudos', 'Instituto Brasileiro de Geografia e Estatística'],
    46: ['Argentina e Uruguai', 'Argentina e Bolívia', 'Bolívia e Uruguai', 'Venezuela e Colômbia', 'Argentina e Uruguai'],
    47: ['Amazônia', 'Mata Atlântica', 'Caatinga', 'Cerrado', 'Caatinga'],
    48: ['República Federativa do Brasil', 'República do Brasil', 'Estados Unidos do Brasil', 'República Presidencialista do Brasil', 'República Federativa do Brasil'],
    49: ['Oscar Niemeyer', 'Paulo Mendes da Rocha', 'Lina Bo Bardi', 'Rosa Kliass', 'Lina Bo Bardi'],
    50: ['São Paulo (SP)', 'Rio de Janeiro (RJ)', 'Petrópolis (RJ)', 'Brasília (DF)', 'Petrópolis (RJ)']
}

RespostaBRES = {
     1: ['Acarajé', 'Cachorro-quente', 'Fogaça', 'Moqueca', 'Acarajé'],
    2: ['Coxinha', 'Pão de queijo', 'Empada', 'Pastel', 'Pão de queijo'],
    3: ['Misto quente', 'Beirute', 'X-burguer', 'Bauru', 'Bauru'],
    4: ['Tacacá', 'Acarajé', 'Caruru', 'Virado à paulista', 'Virado à paulista'],
    5: ['Feijoada', 'Moqueca', 'Tutu de feijão', 'Baião de dois', 'Feijoada'],
    6: ['Festa Junina', 'Carnaval', 'Semana Santa', 'Festa do Bonfim', 'Carnaval'],
    7: ['Festa do Peão', 'Bumba meu Boi', 'Congada', 'Festa Junina', 'Festa Junina'],
    8: ['Salvador', 'Feira de Santana', 'Porto Seguro', 'Presidente Dutra', 'Salvador'],
    9: ['Mato Grosso', 'Paraná', 'Santa Catarina', 'Minas Gerais', 'Paraná'],
    10: ['Pão de Açúcar', 'Pico da Bandeira', 'Catedral da Sé', 'Cristo Redentor', 'Cristo Redentor'],
    11: ['Minas Gerais', 'Rio de Janeiro', 'Amazonas', 'Goiás', 'Minas Gerais'],
    12: ['Boitatá', 'Curupira', 'Mula sem Cabeça', 'Boto-cor-de-rosa', 'Mula sem Cabeça'],
    13: ['Carlos Drummond de Andrade', 'Manuel Bandeira', 'Mário de Andrade', 'Machado de Assis', 'Machado de Assis'],
    14: ['Tim Maia', 'Jorge Ben Jor', 'Chico Buarque', 'Wilson Simonal', 'Jorge Ben Jor'],
    15: ['Papa-Figo ou Homem do Saco', 'Cuca', 'Iara', 'Caboclo d’Água', 'Cuca'],
    16: ['Tom Jobim', 'Caetano Veloso', 'Toquinho', 'João Gilberto', 'Tom Jobim'],
    17: ['Carta das Nações Unidas', 'Carta da Terra', 'Acordo Ortográfico de 1990', 'Pacto do ABC', 'Carta da Terra'],
    18: ['Pantanal', 'Pampas', 'Caatinga', 'Amazônia', 'Amazônia'],
    19: ['Desenvolvimento Alimentar', 'Acordo Nuclear', 'Plano Educacional', 'Desenvolvimento Sustentável', 'Desenvolvimento Sustentável'],
    20: ['Boto cor-de-rosa', 'Boiuna', 'Iara', 'Mapinguari', 'Iara'],
    21: ['São Paulo', 'Belo Horizonte', 'Brasília', 'Salvador', 'São Paulo'],
    22: ['Terra de Santa Cruz', 'Ilha de Vera Cruz', 'Estados Unidos do Brasil', 'Reino Unido de Portugal, Brasil e Algarves', 'Ilha de Vera Cruz'],
    23: ['Dom Pedro II', 'Marechal Deodoro da Fonseca', 'Getúlio Vargas', 'Itamar Franco', 'Marechal Deodoro da Fonseca'],
    24: ['Amazonas', 'Bahia', 'Mato Grosso', 'Pará', 'Amazonas'],
    25: ['Palmeiras', 'Cruzeiro', 'Santos', 'São Paulo', 'Santos'],
    26: ['Dom Pedro I', 'Pedro Álvares Cabral', 'Dom Pedro II', 'Marechal Deodoro', 'Dom Pedro I'],
    27: ['Xaxado', 'Frevo', 'Maxixe', 'Samba', 'Samba'],
    28: ['São Paulo', 'Rio de Janeiro', 'Salvador', 'Brasília', 'Brasília'],
    29: ['2016', '2010', '2014', '2008', '2016'],
    30: ['Anvisa', 'IBGE', 'IML', 'SUS', 'SUS'],
    31: ['Programa Nacional de Imunizações (PNI)', 'Registro Nacional de Doadores de Medula Óssea (REDOME)', 'Samu 192', 'RAPS', 'Programa Nacional de Imunizações (PNI)'],
    32: ['Real', 'Cruzeiro', 'Cruzeiro novo', 'Réis', 'Real'],
    33: ['Fernando Collor e Dilma Roussef', 'Dilma Roussef e José Sarney', 'Fernando Collor e Juscelino Kubitschek', 'Itamar Franco e Michel Temer', 'Fernando Collor e Dilma Roussef'],
    34: ['Manaus, Vitória, Fortaleza, Macapá, Goiânia.', 'Manaus, Vitória, Florianópolis, Macapá, Goiânia.', 'Amazônia, Vitória, Curitiba, Boa Vista, Brasília.', 'Rio Branco, Vitória, Porto Velho, Teresina, Distrito Federal.', 'Manaus, Vitória, Florianópolis, Macapá, Goiânia.'],
    35: ['Porto Velho', 'Rio de Janeiro', 'São Paulo', 'Salvador', 'Salvador'],
    36: ['Princesa Isabel', 'D. Leopoldina', 'Pedro I do Brasil', 'Maria Tomásia Figueira Lima', 'Princesa Isabel'],
    37: ['Rio Paraná', 'Rio São Francisco', 'Rio Madeira', 'Rio Amazonas', 'Rio Amazonas'],
    38: ['Nilo Peçanha', 'Getúlio Vargas', 'Eurico Gaspar Dutra', 'Washington Luís', 'Getúlio Vargas'],
    39: ['1950', '1958', '1962', '1954', '1958'],
    40: ['Alagoas', 'Paraná', 'Sergipe', 'Acre', 'Sergipe'],
    41: ['Bolívia', 'Paraguai', 'Venezuela', 'Colombia', 'Paraguai'],
    42: ['Samba', 'Carimbó', 'Baião', 'Frevo', 'Frevo'],
    43: ['Elevador de Salvador', 'Elevador de Matte', 'Elevador Lacerda', 'Elevador Municipal', 'Elevador Lacerda'],
    44: ['Maior país do mundo', '3º maior país do mundo', '5º maior país do mundo', 'd) 6º maior país do mundo', '5º maior país do mundo'],
    45: ['Instituto Brasileiro de Geografia e Estatística', 'Instituto Brasileiro de Geometria e Estatística', 'Instituto do Brasil Geológico Estadual', 'Instituição Brasileira de Gráficos e Estudos', 'Instituto Brasileiro de Geografia e Estatística'],
    46: ['Argentina e Uruguai', 'Argentina e Bolívia', 'Bolívia e Uruguai', 'Venezuela e Colômbia', 'Argentina e Uruguai'],
    47: ['Amazônia', 'Mata Atlântica', 'Caatinga', 'Cerrado', 'Caatinga'],
    48: ['República Federativa do Brasil', 'República do Brasil', 'Estados Unidos do Brasil', 'República Presidencialista do Brasil', 'República Federativa do Brasil'],
    49: ['Oscar Niemeyer', 'Paulo Mendes da Rocha', 'Lina Bo Bardi', 'Rosa Kliass', 'Lina Bo Bardi'],
    50: ['São Paulo (SP)', 'Rio de Janeiro (RJ)', 'Petrópolis (RJ)', 'Brasília (DF)', 'Petrópolis (RJ)']
}

RespostaEQPT = {
    1: ['Ceviche', 'Fritada', 'Moqueca', 'Seco de Guanta', 'Moqueca'],
    2: ['Cazuela de Mariscos', 'Locro', 'Maito de Pescado', 'Ceviche', 'Locro'],
    3: ['Colada Morada Con Guagua de Pan', 'Higos con Queso', 'Flan de Coco', 'Cocadas Blancas Y Cocadas Negras', 'Colada Morada Con Guagua de Pan'],
    4: ['Cazuela de Mariscos', 'Viche de Pescado', 'Caldo de Corroncho', 'Seco de Guanta', 'Seco de Guanta'],
    5: ['Verde', 'Casabe de Yuca', 'Maito de Pescado', 'Viche Pescado', 'Casabe de Yuca'],
    6: ['Paseo del Chagra', 'Rodeo Montubio', 'Pawkar raymi', 'Amorfinos', 'Rodeo Montubio'],
    7: ['Killa Raymi', 'Kasama ', 'Fiesta de la Chonta', 'Fiesta de la Jora', 'Killa Raymi'],
    8: ['Fiesta de las cruces', 'Fiesta de la Jora ', 'Fiesta del Yamor', 'Fiesta de la Chonta', 'Fiesta del Yamor'],
    9: ['Kasama', 'Pases del Niño ', 'Inti Raymi', 'Año viejo', 'Año viejo'],
    10: ['Pases del Niño', 'La Diablada de Píllaro', 'Cacería del Zorro', 'La Navidad', 'La Diablada de Píllaro'],
    11: ['Cantuña', 'Guagua Auca', 'Lobisomem', 'Kuartam', 'Cantuña'],
    12: ['Olinguito', 'Tubarão-martelo', 'Iguana-marinha', 'Quati', 'Olinguito'],
    13: ['Parque Yasuní', 'Cotopaxi', 'El Cajas', 'Llanganates', 'Parque Yasuní'],
    14: ['Arquipélago de Martim Vaz e Ilha da Trindade', 'Arquipélago de Los Roques', 'Arquipélago de Galápagos', 'Arquipélago Patagônico', 'Arquipélago de Galápagos'],
    15: ['La Diablada de Píllaro', 'Fiesta de la Chonta', 'Fiesta de las flores y las frutas', 'Amorfinos', 'Fiesta de las flores y las frutas'],
    16: ['El Altar', 'Cayambe', 'Cotopaxi', 'Chimborazo', 'Chimborazo'],
    17: ['Praia de Atacames', 'Playa Las Salinas', 'Playa de Chipipe', 'Playa Santa Marianita', 'Praia de Atacames'],
    18: ['Guaiaquil', 'Cuenca', 'Quito', 'Esmeraldas', 'Cuenca'],
    19: ['Ruínas de Machu Picchu', 'Ruínas de Puka Pukara', 'Ruínas de Moray', 'Ruínas de Ingapirca', 'Ruínas de Ingapirca'],
    20: ['Ibarra', 'Cuenca', 'Quito', 'Guaiaquil', 'Quito'],
    21: ['Peso Equatoriano', 'Sucre', 'Dólar Americano', 'Yen', 'Dólar Americano'],
    22: ['Antonio Neumane', 'Eduardo Kingman', 'José Joaquín de Olmedo', 'Arboleda', 'Antonio Neumane'],
    23: ['José María Urvina', 'Juan Javier Espinosa', 'Juan José Flores', 'Luis Cordero Crespo', 'Juan José Flores'],
    24: ['Barcelona de Guaiaquil', 'LDU', 'Emelec', 'Del Valle', 'LDU'],
    25: ['Pastaza', 'Chimborazo', 'Azuay', 'Manabí', 'Pastaza'],
    26: ['Guayas', 'Manabí', 'Los Ríos', 'Tungurahua', 'Guayas'],
    27: ['La Mitad', 'Quayaquil', 'Quito', 'Cuenca', 'Quito'],
    28: ['Selva', 'Oriente', 'Andalucia', 'El porvenir', 'Oriente'],
    29: ['Peru e Colombia', 'Venezuela e Colombia', 'Peru e Chile', 'Bolivia e Argentina', 'Peru e Colombia'],
    30: ['Nina Pacari', 'Ivonne Baki', 'Rosalia Arteaga', 'Joyce de Ginatta', 'Rosalia Arteaga'],
    31: ['Peru', 'Colômbia', 'Venezuela', 'Estados Unidos', 'Peru'],
    32: ['Asturias', 'Chimborazo', 'Imbabura', 'Sucumbios', 'Asturias'],
    33: ['Esfera FAYAC', 'HandEyes', 'Mutagénesis inductiva', 'UPL', 'HandEyes'],
    34: ['Hand and Hope', 'Inversiones realizadas por el INIAP', 'Esfera FAYAC', 'HandEyes', 'Esfera FAYAC'],
    35: ['Chupador de Caracol', 'Salamandra de ojos saltones', 'Sapo punta de flecha', 'Olinguito', 'Olinguito'],
    36: ['9', '14', '12', '25', '12'],
    37: ['Bono geográfico', 'Recargo', 'Subvención de salario', 'Inversión', 'Bono geográfico'],
    38: ['Batalha de Pichincha', 'Batalha da Independência', 'Batalha de Quito', 'Batalha do Vulcão', 'Batalha de Pichincha'],
    39: ['Diego de Almagro', 'Charles Darwin', 'Francisco Pizarro', 'Frei Tomás de Berlanga', 'Frei Tomás de Berlanga'],
    40: ['Lago Cuicocha', 'Lago San Pablo', 'Lago Mojanda', 'Lago Quilotoa', 'Lago Quilotoa'],
    41: ['Oceano Pacífico', 'Oceano Atlântico', 'Oceano índico', 'Oceano Antártico', 'Oceano Pacífico'],
    42: ['Monumento del Ecuador', 'Mitad del Mundo', 'Monumento da Linha do Equador', 'Mitad del Ecuador', 'Mitad del Mundo'],
    43: ['Deep Blue Sea', 'Chapéu-Panamá', 'Cartola', 'Fedora', 'Chapéu-Panamá'],
    44: ['Clorofito', 'Lambari', 'Orquídea', 'Rosa', 'Orquídea'],
    45: ['Águia', 'Canário', 'Condor-dos-andes (Cóndor de los andes)', 'Quebra-Nozes', 'Águia'],
    46: ['Macuxi', 'Oiapoque', 'Guarani', 'Quíchua', 'Quíchua'],
    47: ['Fiesta de La Chonta', 'Pawkar Raymi', 'Fiesta del Yamor', 'Kasama', 'Pawkar Raymi'],
    48: ['Cotopaxi', 'Chimborazo', 'Loja', 'Pichincha', 'Cotopaxi'],
    49: ['Apalaches', 'Andes', 'Montanhas Rochosas', 'Atlas', 'Andes'],
    50: ['Venezuela, Colômbia, Panamá', 'Venezuela, Colômbia e Peru', 'Colômbia, Peru e Panamá', 'Venezuela, Peru e Panamá', 'Venezuela, Colômbia, Panamá']
}

RespostaEQES = {
    1: ['Ceviche', 'Fritada', 'Moqueca', 'Seco de Guanta', 'Moqueca'],
    2: ['Cazuela de Mariscos', 'Locro', 'Maito de Pescado', 'Ceviche', 'Locro'],
    3: ['Colada Morada Con Guagua de Pan', 'Higos con Queso', 'Flan de Coco', 'Cocadas Blancas Y Cocadas Negras', 'Colada Morada Con Guagua de Pan'],
    4: ['Cazuela de Mariscos', 'Viche de Pescado', 'Caldo de Corroncho', 'Seco de Guanta', 'Seco de Guanta'],
    5: ['Verde', 'Casabe de Yuca', 'Maito de Pescado', 'Viche Pescado', 'Casabe de Yuca'],
    6: ['Paseo del Chagra', 'Rodeo Montubio', 'Pawkar raymi', 'Amorfinos', 'Rodeo Montubio'],
    7: ['Killa Raymi', 'Kasama ', 'Fiesta de la Chonta', 'Fiesta de la Jora', 'Killa Raymi'],
    8: ['Fiesta de las cruces', 'Fiesta de la Jora ', 'Fiesta del Yamor', 'Fiesta de la Chonta', 'Fiesta del Yamor'],
    9: ['Kasama', 'Pases del Niño ', 'Inti Raymi', 'Año viejo', 'Año viejo'],
    10: ['Pases del Niño', 'La Diablada de Píllaro', 'Cacería del Zorro', 'La Navidad', 'La Diablada de Píllaro'],
    11: ['Cantuña', 'Guagua Auca', 'Lobisomem', 'Kuartam', 'Cantuña'],
    12: ['Olinguito', 'Tubarão-martelo', 'Iguana-marinha', 'Quati', 'Olinguito'],
    13: ['Parque Yasuní', 'Cotopaxi', 'El Cajas', 'Llanganates', 'Parque Yasuní'],
    14: ['Arquipélago de Martim Vaz e Ilha da Trindade', 'Arquipélago de Los Roques', 'Arquipélago de Galápagos', 'Arquipélago Patagônico', 'Arquipélago de Galápagos'],
    15: ['La Diablada de Píllaro', 'Fiesta de la Chonta', 'Fiesta de las flores y las frutas', 'Amorfinos', 'Fiesta de las flores y las frutas'],
    16: ['El Altar', 'Cayambe', 'Cotopaxi', 'Chimborazo', 'Chimborazo'],
    17: ['Praia de Atacames', 'Playa Las Salinas', 'Playa de Chipipe', 'Playa Santa Marianita', 'Praia de Atacames'],
    18: ['Guaiaquil', 'Cuenca', 'Quito', 'Esmeraldas', 'Cuenca'],
    19: ['Ruínas de Machu Picchu', 'Ruínas de Puka Pukara', 'Ruínas de Moray', 'Ruínas de Ingapirca', 'Ruínas de Ingapirca'],
    20: ['Ibarra', 'Cuenca', 'Quito', 'Guaiaquil', 'Quito'],
    21: ['Peso Equatoriano', 'Sucre', 'Dólar Americano', 'Yen', 'Dólar Americano'],
    22: ['Antonio Neumane', 'Eduardo Kingman', 'José Joaquín de Olmedo', 'Arboleda', 'Antonio Neumane'],
    23: ['José María Urvina', 'Juan Javier Espinosa', 'Juan José Flores', 'Luis Cordero Crespo', 'Juan José Flores'],
    24: ['Barcelona de Guaiaquil', 'LDU', 'Emelec', 'Del Valle', 'LDU'],
    25: ['Pastaza', 'Chimborazo', 'Azuay', 'Manabí', 'Pastaza'],
    26: ['Guayas', 'Manabí', 'Los Ríos', 'Tungurahua', 'Guayas'],
    27: ['La Mitad', 'Quayaquil', 'Quito', 'Cuenca', 'Quito'],
    28: ['Selva', 'Oriente', 'Andalucia', 'El porvenir', 'Oriente'],
    29: ['Peru e Colombia', 'Venezuela e Colombia', 'Peru e Chile', 'Bolivia e Argentina', 'Peru e Colombia'],
    30: ['Nina Pacari', 'Ivonne Baki', 'Rosalia Arteaga', 'Joyce de Ginatta', 'Rosalia Arteaga'],
    31: ['Peru', 'Colômbia', 'Venezuela', 'Estados Unidos', 'Peru'],
    32: ['Asturias', 'Chimborazo', 'Imbabura', 'Sucumbios', 'Asturias'],
    33: ['Esfera FAYAC', 'HandEyes', 'Mutagénesis inductiva', 'UPL', 'HandEyes'],
    34: ['Hand and Hope', 'Inversiones realizadas por el INIAP', 'Esfera FAYAC', 'HandEyes', 'Esfera FAYAC'],
    35: ['Chupador de Caracol', 'Salamandra de ojos saltones', 'Sapo punta de flecha', 'Olinguito', 'Olinguito'],
    36: ['9', '14', '12', '25', '12'],
    37: ['Bono geográfico', 'Recargo', 'Subvención de salario', 'Inversión', 'Bono geográfico'],
    38: ['Batalha de Pichincha', 'Batalha da Independência', 'Batalha de Quito', 'Batalha do Vulcão', 'Batalha de Pichincha'],
    39: ['Diego de Almagro', 'Charles Darwin', 'Francisco Pizarro', 'Frei Tomás de Berlanga', 'Frei Tomás de Berlanga'],
    40: ['Lago Cuicocha', 'Lago San Pablo', 'Lago Mojanda', 'Lago Quilotoa', 'Lago Quilotoa'],
    41: ['Oceano Pacífico', 'Oceano Atlântico', 'Oceano índico', 'Oceano Antártico', 'Oceano Pacífico'],
    42: ['Monumento del Ecuador', 'Mitad del Mundo', 'Monumento da Linha do Equador', 'Mitad del Ecuador', 'Mitad del Mundo'],
    43: ['Deep Blue Sea', 'Chapéu-Panamá', 'Cartola', 'Fedora', 'Chapéu-Panamá'],
    44: ['Clorofito', 'Lambari', 'Orquídea', 'Rosa', 'Orquídea'],
    45: ['Águia', 'Canário', 'Condor-dos-andes (Cóndor de los andes)', 'Quebra-Nozes', 'Águia'],
    46: ['Macuxi', 'Oiapoque', 'Guarani', 'Quíchua', 'Quíchua'],
    47: ['Fiesta de La Chonta', 'Pawkar Raymi', 'Fiesta del Yamor', 'Kasama', 'Pawkar Raymi'],
    48: ['Cotopaxi', 'Chimborazo', 'Loja', 'Pichincha', 'Cotopaxi'],
    49: ['Apalaches', 'Andes', 'Montanhas Rochosas', 'Atlas', 'Andes'],
    50: ['Venezuela, Colômbia, Panamá', 'Venezuela, Colômbia e Peru', 'Colômbia, Peru e Panamá', 'Venezuela, Peru e Panamá', 'Venezuela, Colômbia, Panamá']
}